#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : ktp-contact-list
Version  : 19.08.1
Release  : 6
URL      : https://download.kde.org/stable/applications/19.08.1/src/ktp-contact-list-19.08.1.tar.xz
Source0  : https://download.kde.org/stable/applications/19.08.1/src/ktp-contact-list-19.08.1.tar.xz
Source1 : https://download.kde.org/stable/applications/19.08.1/src/ktp-contact-list-19.08.1.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: ktp-contact-list-bin = %{version}-%{release}
Requires: ktp-contact-list-data = %{version}-%{release}
Requires: ktp-contact-list-license = %{version}-%{release}
Requires: ktp-contact-list-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : knotifyconfig-dev
BuildRequires : kpeople-dev
BuildRequires : ktp-common-internals-dev
BuildRequires : telepathy-qt-dev

%description
No detailed description available

%package bin
Summary: bin components for the ktp-contact-list package.
Group: Binaries
Requires: ktp-contact-list-data = %{version}-%{release}
Requires: ktp-contact-list-license = %{version}-%{release}

%description bin
bin components for the ktp-contact-list package.


%package data
Summary: data components for the ktp-contact-list package.
Group: Data

%description data
data components for the ktp-contact-list package.


%package license
Summary: license components for the ktp-contact-list package.
Group: Default

%description license
license components for the ktp-contact-list package.


%package locales
Summary: locales components for the ktp-contact-list package.
Group: Default

%description locales
locales components for the ktp-contact-list package.


%prep
%setup -q -n ktp-contact-list-19.08.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567711655
mkdir -p clr-build
pushd clr-build
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1567711655
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ktp-contact-list
cp COPYING %{buildroot}/usr/share/package-licenses/ktp-contact-list/COPYING
pushd clr-build
%make_install
popd
%find_lang ktp-contactlist

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ktp-contactlist

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.ktpcontactlist.desktop
/usr/share/dbus-1/services/org.kde.ktpcontactlist.service

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ktp-contact-list/COPYING

%files locales -f ktp-contactlist.lang
%defattr(-,root,root,-)

